### ISSUE TITLE
大佬，keepalive如何完成呢？

### ISSUE THREAD

**Issue by 11003** [gmingchen/vue3-element-plus-admin#36]
![image](https://github.com/gmingchen/agile-admin/assets/35055270/1c663218-2498-4328-ad51-569ee193ba9a)
![image](https://github.com/gmingchen/agile-admin/assets/35055270/9c88e0ed-2dbc-477b-ad6a-d59a952fae07)
![image](https://github.com/gmingchen/agile-admin/assets/35055270/c02a15a7-27ac-4975-bb0c-420221aac622)

**Comment by gmingchen** [comment]
菜单里面可以设置是否缓存

**Comment by 11003** [comment]
设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟`path`同级的。
![image](https://github.com/user-attachments/assets/8af44ac4-abc0-4e73-98eb-e55c808a64bb)
![image](https://github.com/user-attachments/assets/65b00efe-c2d1-4261-a191-da5e1f104653)

**Comment by 11003** [comment]
@gmingchen

**Comment by 984507092** [comment]
没太理解你的意思，请用下中文谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmingchen/agile-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月13日(星期三) 下午3:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36)





 
@gmingchen

**Comment by 11003** [comment]
> 设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟`path`同级的。

设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。

**Comment by 11003** [comment]
> 没太理解你的意思，请用下中文谢谢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" ***@***.***&gt;; 发送时间:&nbsp;2024年11月13日(星期三) 下午3:39 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) @gmingchen — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。

**Comment by gmingchen** [comment]
??
&nbsp;


帅宸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月15日(星期五) 下午4:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36)














  
没太理解你的意思，请用下中文谢谢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" @.&gt;; 发送时间:&nbsp;2024年11月13日(星期三) 下午3:39 @.&gt;; @.&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) @gmingchen — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。

**Comment by gmingchen** [comment]
> @gmingchen
是要在 后台配置了缓存才行的

**Comment by gmingchen** [comment]
> 设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟`path`同级的。 ![image](https://private-user-images.githubusercontent.com/35055270/385163743-8af44ac4-abc0-4e73-98eb-e55c808a64bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjYxNTIsIm5iZiI6MTczMTY2NTg1MiwicGF0aCI6Ii8zNTA1NTI3MC8zODUxNjM3NDMtOGFmNDRhYzQtYWJjMC00ZTczLTk4ZWItZTU1YzgwOGE2NGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEwMTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYjdkNDNkOGU1ZWFhYjEzNWEyNDI5ZmE1ODIwZTA3N2U5ODU2MjhjMmNhMjc2ZGVmNWE1MmIxYjkxMDRmMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dkLdCkv-Kt2JKe6y_qfbu96x5dJa9irBPxXCbOWXXvk) ![image](https://private-user-images.githubusercontent.com/35055270/385163809-65b00efe-c2d1-4261-a191-da5e1f104653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjYxNTIsIm5iZiI6MTczMTY2NTg1MiwicGF0aCI6Ii8zNTA1NTI3MC8zODUxNjM4MDktNjViMDBlZmUtYzJkMS00MjYxLWExOTEtZGE1ZTFmMTA0NjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEwMTczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllYmYxNDEwYjQ4ZjYyODdhYzVhZWUxMjgwNDliY2QwNmRmNDQ4ZWYwMjhiNWY0NTNkZjVmOWVjNjBkODQwMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nqfo2huy-Zo1o3pKR51V3nL7sXBUub3qWiVXQXFfJ9A)
数据是请求接口的， 会根据接口响应参数动态创建路由的，可以参考线上项目的 演示模块 > 嵌套路由演示 页面

**Comment by 984507092** [comment]
你是想要什么功能呢，或者说你打算用keep-live完成什么呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmingchen/agile-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月15日(星期五) 晚上6:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36)





  
设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。  
 数据是请求接口的， 会根据接口响应参数动态创建路由的，可以参考线上项目的 演示模块 &gt; 嵌套路由演示 页面

**Comment by 11003** [comment]
> 你是想要什么功能呢，或者说你打算用keep-live完成什么呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" ***@***.***&gt;; 发送时间:&nbsp;2024年11月15日(星期五) 晚上6:24 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) 设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。 数据是请求接口的， 会根据接口响应参数动态创建路由的，可以参考线上项目的 演示模块 &gt; 嵌套路由演示 页面 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

就是从列表第三页进入详情页面，然后退出仍然在第三页

**Comment by 984507092** [comment]
你给我一个联系方式吧，这样说不明白



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LuFei ***@***.***&gt;
发送时间: 2024年11月19日 00:08
收件人: gmingchen/agile-admin ***@***.***&gt;
抄送: heming ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36)





  
你是想要什么功能呢，或者说你打算用keep-live完成什么呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" @.&gt;; 发送时间:&nbsp;2024年11月15日(星期五) 晚上6:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) 设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。 数据是请求接口的， 会根据接口响应参数动态创建路由的，可以参考线上项目的 演示模块 &gt; 嵌套路由演示 页面 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
就是从列表第三页进入详情页面，然后退出仍然在第三页

**Comment by 984507092** [comment]
我邮箱不自己点击进去是收不到消息的，很抱歉啊，keep-alive一般都是用来缓存的，所以如果不是必须用的话你可以先不用，而且一般是
<keepa-live&gt;
<component :is=“组件” /&gt;
</keep-live&gt;
这个组件的内容以及接口什么的会被缓存，在页面中需要使用特定的两个生命周期&nbsp;
这个连接你去看下&nbsp;
KeepAlive | Vue.js (vuejs.org)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gmingchen/agile-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月19日(星期二) 凌晨0:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36)





  
你是想要什么功能呢，或者说你打算用keep-live完成什么呢
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" @.&gt;; 发送时间:&nbsp;2024年11月15日(星期五) 晚上6:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) 设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。 数据是请求接口的， 会根据接口响应参数动态创建路由的，可以参考线上项目的 演示模块 &gt; 嵌套路由演示 页面 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
就是从列表第三页进入详情页面，然后退出仍然在第三页

**Comment by 11003** [comment]
> 我邮箱不自己点击进去是收不到消息的，很抱歉啊，keep-alive一般都是用来缓存的，所以如果不是必须用的话你可以先不用，而且一般是 <keepa-live&gt; <component :is=“组件” /&gt; </keep-live&gt; 这个组件的内容以及接口什么的会被缓存，在页面中需要使用特定的两个生命周期&nbsp; 这个连接你去看下&nbsp; KeepAlive | Vue.js (vuejs.org)
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" ***@***.***&gt;; 发送时间:&nbsp;2024年11月19日(星期二) 凌晨0:08 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) 你是想要什么功能呢，或者说你打算用keep-live完成什么呢 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gmingchen/agile-admin" @.&gt;; 发送时间:&nbsp;2024年11月15日(星期五) 晚上6:24 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [gmingchen/agile-admin] 大佬，keepalive如何完成呢？ (Issue #36) 设置了没有用；我看文档是在meta里面设置的，但是在项目里面是跟path同级的。 数据是请求接口的， 会根据接口响应参数动态创建路由的，可以参考线上项目的 演示模块 &gt; 嵌套路由演示 页面 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; 就是从列表第三页进入详情页面，然后退出仍然在第三页 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

好呢，不用了。大佬 我搞定了
